config/routes.rb
Dessin::Application.routes.draw do

  resources :informations,
    :path => "news",
    :path_names => { :new => 'creer-une-news', :edit => 'modifier-une-news' }

  resources :gallery_categories

  resources :galleries,
    :path => "galerie" do
    resources :medias
    resources :galleries_comment
    member do
      post :add_media
      get :remove_media
      post :add_comment
    end
  end

  devise_path_names = { :sign_in => 'connexion',
    :sign_out => 'deconnexion',
    :password => 'identifiants',
    :confirmation => 'verification',
    :sign_up => 'inscription' }

  devise_for :users,
    :path => "compte",
    :path_names => devise_path_names,
    :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
      get "/compte/mes-donnees-personnelles" => "users/registrations#edit", :as => :private_datas_user
    end

  match '/les-membres/membre/:id' => 'users#show', :as => :user
  match '/les-membres' => 'users#index', :as => :users
  match '/compte/mes-galeries' => 'users#galleries', :as => :galleries_user
  match '/compte/accepter-demande-amis/:id' => 'users#add_friend', :as => :add_friend_user
  match '/compte/supprimer-amis/:id' => 'users#remove_friend', :as => :remove_friend_user
  match '/compte/demande-amis/:id' => 'users#send_friend_request', :as => :send_friend_request
  match '/compte/refuser-demande-amis/:id' => 'users#remove_friend_request', :as => :remove_friend_request_user
  match '/compte/les-demande-amis' => 'users#friend_requests', :as => :friend_requests_user
  match '/compte/mes-amis' => 'users#friends', :as => :friends_user
  match '/compte/envoyer-un-message/:id' => 'users#send_message', :as => :send_message_user
  match '/compte/supprimer-message/:id' => 'users#remove_message', :as => :remove_message_user
  match '/compte/mes-messages' => 'users#messages_recieved', :as => :messages_recieved_user
  match '/compte/les-nouveau-commentaires' => 'users#galleries_commented', :as => :galleries_commented_user
  match '/compte/supprimer-commentaire/:id' => 'users#remove_gallery_comment', :as => :remove_gallery_comment_user
  
  root :to => "home#index"

  resources :forum_parts

end

app/views/forum_parts/_form.html.erb
<%= form_for(@forum_part) do |f| %>
  <% if @forum_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum_part.errors.count, "error") %> prohibited this forum_part from being saved:</h2>

      <ul>
      <% @forum_part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_parts/edit.html.erb
<h1>Editing forum_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_part %> |
<%= link_to 'Back', forum_parts_path %>

app/views/forum_parts/index.html.erb
<h1>Listing forum_parts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forum_parts.each do |forum_part| %>
  <tr>
    <td><%= forum_part.name %></td>
    <td><%= link_to 'Show', forum_part %></td>
    <td><%= link_to 'Edit', edit_forum_part_path(forum_part) %></td>
    <td><%= link_to 'Destroy', forum_part, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum part', new_forum_part_path %>

app/views/forum_parts/new.html.erb
<h1>New forum_part</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_parts_path %>

app/views/forum_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @forum_part.name %>
</p>


<%= link_to 'Edit', edit_forum_part_path(@forum_part) %> |
<%= link_to 'Back', forum_parts_path %>