config/routes.rb
Dessin::Application.routes.draw do

  resources :informations,
    :path => "news",
    :path_names => { :new => 'creer-une-news', :edit => 'modifier-une-news' }

  resources :gallery_categories

  resources :galleries,
    :path => "galerie" do
    resources :medias
    resources :galleries_comment
    member do
      post :add_media
      get :remove_media
      post :add_comment
    end
  end

  devise_path_names = { :sign_in => 'connexion',
    :sign_out => 'deconnexion',
    :password => 'identifiants',
    :confirmation => 'verification',
    :sign_up => 'inscription' }

  devise_for :users,
    :path => "compte",
    :path_names => devise_path_names,
    :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
      get "/compte/mes-donnees-personnelles" => "users/registrations#edit", :as => :private_datas_user
    end

  match '/les-membres/membre/:id' => 'users#show', :as => :user
  match '/les-membres' => 'users#index', :as => :users
  match '/compte/mes-galeries' => 'users#galleries', :as => :galleries_user
  match '/compte/accepter-demande-amis/:id' => 'users#add_friend', :as => :add_friend_user
  match '/compte/supprimer-amis/:id' => 'users#remove_friend', :as => :remove_friend_user
  match '/compte/demande-amis/:id' => 'users#send_friend_request', :as => :send_friend_request
  match '/compte/refuser-demande-amis/:id' => 'users#remove_friend_request', :as => :remove_friend_request_user
  match '/compte/les-demande-amis' => 'users#friend_requests', :as => :friend_requests_user
  match '/compte/mes-amis' => 'users#friends', :as => :friends_user
  match '/compte/envoyer-un-message/:id' => 'users#send_message', :as => :send_message_user
  match '/compte/supprimer-message/:id' => 'users#remove_message', :as => :remove_message_user
  match '/compte/mes-messages' => 'users#messages_recieved', :as => :messages_recieved_user
  match '/compte/les-nouveau-commentaires' => 'users#galleries_commented', :as => :galleries_commented_user
  match '/compte/supprimer-commentaire/:id' => 'users#remove_gallery_comment', :as => :remove_gallery_comment_user
  
  root :to => "home#index"

  resources :forum_parts

end

app/models/user.rb
class User < ActiveRecord::Base
  GENDER = ['m', 'f', 'nc']
  ROLE = {'0' => 'Member', '20' => 'Newser', '100' => 'Administrator'}
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :avatar, :pseudo, :birth_date, :sex, :description, :role, :email, :password, :password_confirmation, :remember_me


  has_many :galleries, :dependent => :destroy

  has_many :friends, :foreign_key => 'user_id'
  has_many :sender_friends_requests, :foreign_key => 'sender_id', :class_name => "FriendRequest"
  has_many :reciever_friends_requests, :foreign_key => 'reciever_id', :class_name => "FriendRequest"
  has_many :messages_recieved, :foreign_key => 'reciever_id', :class_name => "Message"

  has_attached_file :avatar,
    :styles => {:thumb => "150x150#"},
    :url => "/images/avatar/:id/:style_:basename.:extension",
    :path => ":rails_root/public/images/avatar/:id/:style_:basename.:extension",
    :default_url => "/images/avatar/default/avatar_base.jpg"

  def url(*args)
    avatar.url(*args)
  end

  def name
    avatar_file_name
  end

  def content_type
    avatar_content_type
  end

  def size
    avatar_file_size
  end

  validates :pseudo, :presence => true, :uniqueness => true
  validates :birth_date, :presence => true

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users_controller.rb
# coding: utf-8

class UsersController < ApplicationController
  layout :choose_layout
  before_filter :authenticate

  def authenticate
    unless user_signed_in?
      session[:user_return_to] = request.request_uri
      authenticate_user!
    end
  end

  def choose_layout
    if [:send_friend_request, :send_message].include? action_name.to_sym
      'empty'
    else
      'application'
    end
  end

  def index
    @search = User.search(params[:search])
    @users = @search.all.paginate :page => @current_page, :per_page => Gallery.per_page
  end
  
  def show
    @user = User.find(params[:id])
  end

  def galleries
    @gallery = (flash['gallery'] ? flash['gallery'] : Gallery.new )
    @galleries = current_user.galleries

    render "users/galleries/galleries"
  end

  def friend_requests

  end

  def send_friend_request
    reciever = User.find(params[:id])
    unless already_requested_to?(current_user, reciever)
      unless already_requested_to?(reciever, current_user)
        unless are_friends?(current_user, reciever)
          @friend_request = FriendRequest.new()
          if params[:friend_request]
            @friend_request.sender = current_user
            @friend_request.reciever = reciever
            @friend_request.message = params[:friend_request][:message]
            if @friend_request.save
              flash.now[:notice] = "envoyé"
            else
              flash.now[:alert] = "erreur"
            end
          end
        else
          flash.now[:alert] = "vous êtes déja amis avec ce membre"
        end
      else
        flash.now[:alert] = "vous lui avez déja envoyer une demande d'amis"
      end
    else
      flash.now[:alert] = "il vous a déja envoyer une demande d'amis"
    end
  end

  def remove_friend_request
    if @f_request = FriendRequest.find_by_id(params[:id])
      if @f_request.sender == current_user or @f_request.reciever == current_user
        if @f_request.destroy
          flash[:notice] = "la demande à bien été refusé"
        else
          flash[:alert] = "erreur"
        end
      else
        flash[:alert] = "cette demande ne vous appartien pas ou ne vous est pas destinée"
      end
    else
      flash[:alert] = "cette demande n'éxiste pas"
    end
    redirect_to :friend_requests_user
  end

  def friends
    @friends = current_user.friends
  end

  def add_friend
    if params[:id]
      if friend = User.find_by_id(params[:id])
        if friend.id != current_user.id
          unless already_requested_to?(current_user, friend)
            unless are_friends?(current_user, friend)
              friend_record1 = Friend.new(:user => current_user, :fuser => friend)
              friend_record2 = Friend.new(:user => friend, :fuser => current_user)
              if friend_record1.save and friend_record2.save
                flash[:notice] = "vous etes maintenant amis avec #{friend.pseudo}"
              else
                flash[:alert] = "erreur lors de la sauvegarde"
              end
            else
              flash[:alert] = "vous etes déjà amis avec #{friend.pseudo}"
            end
          else
            flash[:alert] = "il faut que #{friend.pseudo} vous envoie une demande d'amis pour pouvoir l'accepter"
          end
        else
          flash[:alert] = "Vous ne pouvais pas être amis avec vous même"
        end
      else
        flash[:alert] = "erreur ce membre n'existe pas"
      end
    end
    redirect_to :friends_user
  end

  def remove_friend
    if fuser = User.find_by_id(params[:id])
      if are_friends?(current_user, fuser)
        f_user = Friend.find_by_user_id_and_fuser_id(current_user.id, fuser.id)
        f_friend = Friend.find_by_user_id_and_fuser_id(fuser.id, current_user.id)
        logger.debug f_friend
        if f_user.delete and f_friend.delete
          flash[:notice] = "vous n'êtes desormais plus amis avec #{fuser.pseudo}"
        else
          flash[:alert] = "erreur lors de la suppriession de votre lien d'amitié"
        end
      else
        flash[:alert] = "vous êtes pas amis avec ce membre"
      end
    else
      flash[:alert] = "erreur ce membre n'existe pas"
    end
    redirect_to :friends_user
  end

  def messages_recieved
    @messages_recieved = current_user.messages_recieved
  end

  def send_message
    reciever = User.find(params[:id])
    @message = Message.new()
    if params[:message]
      @message.sender = current_user
      @message.reciever = reciever
      @message.message = params[:message][:message]
      if @message.save
        flash.now[:notice] = "envoyé"
      else
        flash.now[:alert] = "erreur"
      end
    end
  end

  def remove_message
    if @message = Message.find_by_id(params[:id])
      if @message.reciever == current_user
        if @message.destroy
          flash[:notice] = "message supprimé avec succès"
        else
          flash[:alert] = "erreur"
        end
      else
        flash[:alert] = "Vous n'êtes pas le destinataire de ce message"
      end
    else
      flash[:alert] = "ce message n'existe pas"
    end
    redirect_to :messages_recieved_user
  end

  def galleries_commented
    @galleries_commented = []
    current_user.galleries.each do |gallery|
      @galleries_commented.push(gallery) if gallery.comments.unsee.count > 0
    end
  end

  def remove_gallery_comment
    @gallery_comment = GalleriesComment.find(params[:id])
    if current_user == @gallery_comment.from_user || current_user == @gallery_comment.to_gallery.user
      if @gallery_comment.destroy
        flash[:notice] = "commentaire supprimé avec succès"
      else
        flash[:alert] = "erreur"
      end
    else
      flash[:alert] = "Vous n'avez pas le droits de supprimer ce message"
    end
    redirect_to @gallery_comment.to_gallery, :anchor => "comments"
  end
end

app/views/users/_friend.html.erb
<div class="<%= friend.gender == "nc" ? "white" : friend.gender == "m" ? "blue" : "pink" %>_block_without_corner">
  <div class="title"><%= friend.pseudo %></div>
  <div class="content">
      <%= image_tag friend.avatar.url(:thumb), :width => "80px" %>
      <%= link_to 'Show', user_path(friend) %>
      <%= link_to 'delete', remove_friend_user_path(friend) %>
  </div>
</div>

app/views/users/_gallery_commented.html.erb
<div class="gallery_commented_item">
  <table width="100%">
    <tr height="20px">
      <td rowspan="3" width="130px"><%= image_tag gallery_commented.drawings.last.url(:thumb), :width => 100 %></td>
      <td><%= link_to gallery_commented.name, gallery_commented %></td>
    </tr>
    <tr height="20px">
      <td><%= gallery_commented.comments.unsee.count %> message(s) not see</td>
    </tr>
    <tr height="20px">
      <td><%= link_to "see", gallery_commented, :anchor => "comment_#{gallery_commented.comments.unsee.first.id}" %></td>
    </tr>
  </table>
</div>

app/views/users/_recieved_request.html.erb
<div class="recieved_request_item">
  <table width="100%">
    <tr height="20px">
      <td rowspan="3" width="130px"><%= image_tag recieved_request.sender.avatar.url(:thumb), :width => 100 %></td>
      <td><%= link_to recieved_request.sender.pseudo, recieved_request.sender %></td>
    </tr>
    <tr height="20px">
      <td><%= recieved_request.message %></td>
    </tr>
    <tr height="20px">
      <td><%= link_to "accept", add_friend_user_path(:id => recieved_request.sender.id) %> | <%= link_to "refuse", remove_friend_request_user_path(:id => recieved_request.sender.id) %></td>
    </tr>
  </table>
</div>

app/views/users/_search.html.erb
<div class="white_block_without_corner">
  <div class="title">Filtres de recheche</div>
  <div class="content">
    <%= form_for search, :url => '/les-membres' do |f| %>
      <div class="search_block search_user_pseudo_contains">
        <%= f.label :pseudo_contains %>
        <%= f.text_field :pseudo_contains %>
      </div>
      <div class="search_block search_buttons">
        <%= f.submit "rechercher" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="<%= color %>_block_without_corner">
  <div class="title">
    <%= user.pseudo %>
  </div>
  <div class="content">
    <div class="link">
      <%= link_to 'Show', user_path(:id => user.id) %> |
      <%= link_to 'send message', send_message_user_path(:id => user.id), :rel => 'shadowbox;width=600px;height=400px' %> |
      <%= (link_to 'send friend request', send_friend_request_path(:id => user.id), :rel => 'shadowbox;width=600px;height=400px') unless are_friends?(current_user, user) or current_user == user or already_requested_to?(current_user, user) or already_requested_to?(user, current_user) %>
    </div>
  </div>
</div>

app/views/users/friend_requests.html.erb
<h1 class="content_title">Friend requests</h1>

<div class="blue_block_without_corner">
  <div class="title">requests</div>
  <div class="content">
    <div class="list">
      <%= render :partial => "recieved_request", :collection => current_user.reciever_friends_requests, :spacer_template => 'shared/application/list_spacer' %>
    </div>
  </div>
</div>

app/views/users/friends.html.erb
<h1 class="content_title">My Friends</h1>

<% @friends.each do |fr| %>
  <%= render :partial => "friend", :locals => {:friend => fr.fuser } %>
<% end %>

app/views/users/galleries_commented.html.erb
<h1 class="content_title">Commments posted on my galleries</h1>

<div class="blue_block_without_corner">
  <div class="title">galleries</div>
  <div class="content">
    <div class="list">
      <%= render :partial => "gallery_commented", :collection => @galleries_commented, :spacer_template => 'shared/application/list_spacer' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="content_title">Members</h1>

<%= render :partial => 'search', :locals => {:search => @search} %>

<%= render :collection => @users, :partial => "user", :locals => {:color => cycle("blue", "pink", "white")} %>

app/views/users/messages_recieved.html.erb
<h1 class="content_title">My recieved messages</h1>

<% @messages_recieved.each do |message| %>
  From <%= message.sender.pseudo %><br/>
  at <%= message.created_at %><br/>
  message :<br/>
  <%= message.message %><br/>
  <%= link_to 'Delete', remove_message_user_path(message) %><br/><br/>
<% end %>

app/views/users/send_friend_request.html.erb
<% unless flash[:notice] or flash[:alert] %>
  <%= form_for(@friend_request, :url => send_friend_request_path) do |f| %>
    <% if @friend_request.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@friend_request.errors.count, "error") %> prohibited this forum_part from being saved:</h2>

        <ul>
          <% @friend_request.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :message %><br />
      <%= f.text_area :message, :rows => "15", :cols => "74" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/users/send_message.html.erb
<% unless flash[:notice] or flash[:alert] %>
  <%= form_for(@message, :url => send_message_user_path) do |f| %>
    <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %></h2>

        <ul>
          <% @message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :message %><br />
      <%= f.text_area :message, :rows => "15", :cols => "74" %>
    </div>
    <div class="actions">
      <%= f.submit 'Send message' %>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1 class="content_title"><%= @user.pseudo %></h1>

<div class="blue_block">
  <div class="title">Informations</div>
  <div class="content">
      <p><%= image_tag @user.avatar.url(:thumb) %></p>
      <%#= years = Time.now.year - @user.birth_date.to_date.year %>
      <p><%= Time.now.year - @user.birth_date.to_date.year %> years old</p>
      <p><%= I18n.t("gender.#{@user.gender}") %></p>
      <p><%= @user.description %></p>
  </div>
</div>
<div class="blue_block_footer">
  <div class="block">
    <div class="link">
      <%= link_to 'send message', send_message_user_path(:id => @user.id), :rel => 'shadowbox;width=600px;height=400px' %> |
      <%= (link_to 'send friend request', send_friend_request_path(:id => @user.id), :rel => 'shadowbox;width=600px;height=400px') unless are_friends?(current_user, @user) or current_user == @user or already_requested_to?(current_user, @user) or already_requested_to?(@user, current_user) %>
    </div>
  </div>
</div>

<h2 class="content_title">Galleries</h2>

<%= render :collection => @user.galleries, :partial => "galleries/gallery", :locals => {:color => cycle("blue", "pink", "white")} %>