config/routes.rb
Dessin::Application.routes.draw do

  resources :informations,
    :path => "news",
    :path_names => { :new => 'creer-une-news', :edit => 'modifier-une-news' }

  resources :gallery_categories

  resources :galleries,
    :path => "galerie" do
    resources :medias
    resources :galleries_comment
    member do
      post :add_media
      get :remove_media
      post :add_comment
    end
  end

  devise_path_names = { :sign_in => 'connexion',
    :sign_out => 'deconnexion',
    :password => 'identifiants',
    :confirmation => 'verification',
    :sign_up => 'inscription' }

  devise_for :users,
    :path => "compte",
    :path_names => devise_path_names,
    :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
      get "/compte/mes-donnees-personnelles" => "users/registrations#edit", :as => :private_datas_user
    end

  match '/les-membres/membre/:id' => 'users#show', :as => :user
  match '/les-membres' => 'users#index', :as => :users
  match '/compte/mes-galeries' => 'users#galleries', :as => :galleries_user
  match '/compte/accepter-demande-amis/:id' => 'users#add_friend', :as => :add_friend_user
  match '/compte/supprimer-amis/:id' => 'users#remove_friend', :as => :remove_friend_user
  match '/compte/demande-amis/:id' => 'users#send_friend_request', :as => :send_friend_request
  match '/compte/refuser-demande-amis/:id' => 'users#remove_friend_request', :as => :remove_friend_request_user
  match '/compte/les-demande-amis' => 'users#friend_requests', :as => :friend_requests_user
  match '/compte/mes-amis' => 'users#friends', :as => :friends_user
  match '/compte/envoyer-un-message/:id' => 'users#send_message', :as => :send_message_user
  match '/compte/supprimer-message/:id' => 'users#remove_message', :as => :remove_message_user
  match '/compte/mes-messages' => 'users#messages_recieved', :as => :messages_recieved_user
  match '/compte/les-nouveau-commentaires' => 'users#galleries_commented', :as => :galleries_commented_user
  match '/compte/supprimer-commentaire/:id' => 'users#remove_gallery_comment', :as => :remove_gallery_comment_user
  
  root :to => "home#index"

  resources :forum_parts

end

app/models/information.rb
class Information < ActiveRecord::Base
  set_table_name 'informations'

  belongs_to :writer, :class_name => "User"
end

app/controllers/informations_controller.rb
# coding: utf-8

class InformationsController < ApplicationController
  before_filter :authenticate, :only => [:create, :uptade, :edit, :destroy]

  def authenticate
    unless user_signed_in?
      session[:user_return_to] = request.request_uri
      authenticate_user!
    end
  end

  # GET /informations
  def index
    @informations = Information.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /informations/1
  def show
    @information = Information.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /informations/new
  def new
    @information = Information.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /informations
  def create
    @information = Information.new(params[:information])
    @information.writer = current_user
    if @information.valid?
      if @information.save
        @information = Information.new
        flash[:notice] = "Dossier créer avec succès"
      else
        flash[:alert] = "une errieur est survenue lors de l'enregistrement"
      end
    else
      flash['information'] = @information
    end
    redirect_to informations_path
  end

  # GET /informations/1
  def edit
    @information = Information.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # PUT /informations/1
  def update
    if @information = Information.find_by_id(params[:id])
      if @information.update_attributes(params[:information])
        redirect_to(@information, :notice => 'Information was successfully updated.')
      else
        redirect_to(edit_information_path(@information), :alert => 'Error in update')
      end
    else
      redirect_to informations_path, :alert => "This information don't exist"
    end
  end

  def destroy
    if @information = Information.find_by_id(params[:id])
      if @information.destroy
        flash[:notice] = "Information was deleted sucessfully"
      else
        flash[:alert] = "Information can't be deleted"
      end
    else
      flash[:alert] = "This information not exist"
    end
    redirect_to informations_path
  end

end

app/views/informations/_information.html.erb
<% color = cycle("blue", "pink", "white") %>
<div class="<%= color %>_block">
  <div class="title">
    <%= information.title %>
  </div>
  <div class="content">
    <%= information.content %>
  </div>
</div>
<div class="<%= color %>_block_footer">
  <div class="block">
    <div class="link">
      <%= link_to 'Show', information_path(information.id) %>
    </div>
  </div>
</div>

app/views/informations/edit.html.erb
<h1 class="content_title">Editing News</h1>

<div class="blue_block_without_corner">
  <div class="title">News Form</div>
  <div class="content">
    <%= form_for(@information,:url => {:action => "update", :controller=>"informations"}) do |f| %>
      <%= form_errors! @information %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_area :content %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @ninformation %> |
<%= link_to 'Back', informations_path %>

app/views/informations/index.html.erb
<h1 class="content_title">News List</h1>

<%= link_to 'New Information', new_information_path %>

<%= render :collection => @informations, :partial => "information" %>

app/views/informations/new.html.erb
<h1 class="content_title">Add a News</h1>

<div class="blue_block_without_corner">
  <div class="title">News Form</div>
  <div class="content">
    <%= form_for(@information,:url => {:action => "create", :controller => "informations"}) do |f| %>
      <%= form_errors! @information %>

      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_area :content %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back', informations_path %>

app/views/informations/show.html.erb
<div class="blue_block">
  <div class="title">
    <%= @information.title %>
  </div>
  <div class="content">
    <%= @information.content %>
  </div>
</div>
<div class="blue_block_footer">
  <div class="block">
    <div class="links" style="float:left">
      <%= link_to 'Edit', edit_information_path(@information) %> |
      <%= link_to 'Back', informations_path %>
    </div>
    <div class="author" style="float:right">
      <%= @information.writer.pseudo %>
    </div>
  </div>
</div>