config/routes.rb
Dessin::Application.routes.draw do

  resources :informations,
    :path => "news",
    :path_names => { :new => 'creer-une-news', :edit => 'modifier-une-news' }

  resources :gallery_categories

  resources :galleries,
    :path => "galerie" do
    resources :medias
    resources :galleries_comment
    member do
      post :add_media
      get :remove_media
      post :add_comment
    end
  end

  devise_path_names = { :sign_in => 'connexion',
    :sign_out => 'deconnexion',
    :password => 'identifiants',
    :confirmation => 'verification',
    :sign_up => 'inscription' }

  devise_for :users,
    :path => "compte",
    :path_names => devise_path_names,
    :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" } do
      get "/compte/mes-donnees-personnelles" => "users/registrations#edit", :as => :private_datas_user
    end

  match '/les-membres/membre/:id' => 'users#show', :as => :user
  match '/les-membres' => 'users#index', :as => :users
  match '/compte/mes-galeries' => 'users#galleries', :as => :galleries_user
  match '/compte/accepter-demande-amis/:id' => 'users#add_friend', :as => :add_friend_user
  match '/compte/supprimer-amis/:id' => 'users#remove_friend', :as => :remove_friend_user
  match '/compte/demande-amis/:id' => 'users#send_friend_request', :as => :send_friend_request
  match '/compte/refuser-demande-amis/:id' => 'users#remove_friend_request', :as => :remove_friend_request_user
  match '/compte/les-demande-amis' => 'users#friend_requests', :as => :friend_requests_user
  match '/compte/mes-amis' => 'users#friends', :as => :friends_user
  match '/compte/envoyer-un-message/:id' => 'users#send_message', :as => :send_message_user
  match '/compte/supprimer-message/:id' => 'users#remove_message', :as => :remove_message_user
  match '/compte/mes-messages' => 'users#messages_recieved', :as => :messages_recieved_user
  match '/compte/les-nouveau-commentaires' => 'users#galleries_commented', :as => :galleries_commented_user
  match '/compte/supprimer-commentaire/:id' => 'users#remove_gallery_comment', :as => :remove_gallery_comment_user
  
  root :to => "home#index"

  resources :forum_parts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery

  def after_update_path_for(resource)
    private_datas_user_path
  end

  def after_sign_in_path_for(resource)
    private_datas_user_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def are_friends?(user1, user2)
    if Friend.find_by_user_id_and_fuser_id(user1.id, user2.id)
      return true
    else
      return false
    end
  end

  def already_requested_to?(user1, user2)
    if FriendRequest.find_by_sender_id_and_reciever_id(user1, user2)
      return true
    else
      return false
    end
  end

  def set_date_format(date,format)
    return date.strftime(format)
  end

  def get_time(date)
    return date.strftime("%H\:%M")
  end

  def devise_errors!
    format_errors(resource)
  end

  def form_errors!(form)
    format_errors(form)
  end

  def format_errors(object)
    return "" if object.errors.empty?

    messages = object.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "#{pluralize(object.errors.count, "erreur")}"

    html = <<-HTML
<div id="error_explanation">
<h3>#{sentence}</h3>
<ul>#{messages}</ul>
</div>
    HTML

    html.html_safe
  end

  def format_keywords(keywords_string)
    keywords = []
    keywords_string.split(',').each do |keyword|
      keywords.push(I18n.t("keywords.#{keyword}"))
    end
    return keywords * ', '
  end
end

app/views/shared/application/_header.html.erb
<div id="header">
  <div class="logo"></div>
</div>

app/views/shared/application/_list_spacer.html.erb
<div class="list_spacer"></div>

app/views/shared/application/_menu_left.html.erb
<div id="menu_left">
  <% if current_user && current_user.role > 80 %>
    <div class="pink_block_without_corner">
      <div class="title">Administration</div>
      <div class="content">
        <ul>
          <li><%= link_to "News", informations_path %></li>
          <li><%= link_to "Signalement", "" %></li>
          <li><%= link_to "Message", "" %></li>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="white_block_without_corner">
    <div class="title">Mon compte</div>
    <div class="content">
      <ul>
        <% unless user_signed_in? %>
          <li><%= link_to "Connexion", new_user_session_path %></li>
          <li><%= link_to "Inscription", new_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Déconnexion", destroy_user_session_path %></li>
          <li><%= link_to "Mes identifiants", private_datas_user_path %></li>
          <li><%= link_to "Mes galeries", galleries_user_path %></li>
          <li><%= link_to "Mes cours", "" %></li>
          <li><%= link_to "Mes messages", messages_recieved_user_path %></li>
          <li><%= link_to "Les demande d'amis", friend_requests_user_path %></li>
          <li><%= link_to "Mes amis", friends_user_path %></li>
          <li><%= link_to "Les commentaires", galleries_commented_user_path %></li>
          <li><%= link_to "Mes sujets", "" %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="blue_block_without_corner">
    <div class="title">Galeries</div>
    <div class="content">
      <ul>
        <% App::GalleryKeywords.each do |keyword| %>
          <li><%= link_to I18n.t("keywords.#{keyword}"), galleries_path("search[keywords_contains_any(#{App::GalleryKeywords.index(keyword)+1})]" => keyword) %></li>
        <% end %>
        <li><%= link_to "Toutes", galleries_path %></li>
      </ul>
    </div>
  </div>
  <!--
  <div class="pink_block_without_corner">
    <div class="title">Aide et Cours</div>
    <div class="content">
      <ul>
        <li><%= link_to "Dessin", "" %></li>
        <li><%= link_to "Manga", "" %></li>
        <li><%= link_to "Peinture", "" %></li>
        <li>etc</li>
        <li><%= link_to "Toutes", "" %></li>
      </ul>
    </div>
  </div>
  -->
</div>

app/views/shared/application/_menu_top.html.erb
<div id="menu_top">
  <div class="item"><%= link_to "accueil", root_path %></div>
  <div class="item">Cours</div>
  <div class="item"><%= link_to "gallerie", galleries_path %></div>
  <div class="item"><%= link_to "membres", users_path %></div>
  <div class="item">Forum</div>
</div>